project:
  type: book
  output-dir: docs

book:
  title: "REDCap R Handbook"
  author: "Andreas Gammelgaard Damsbo"
  date: today
  status: "drafting"
  search: true
  repo-url: https://github.com/agdamsbo/redcap-r-handbook/
  repo-actions: [edit]
  site-url: https://agdamsbo.github.io/redcap-r-handbook/
  chapters:
    - index.qmd
    - access.qmd
    - part: datahandling.qmd
      chapters:
        - acquisition.qmd
    - part: database.qmd
      chapters:
        - dataset.qmd
        - scratch.qmd
        - advanced.qmd
  appendices:
    - references.qmd
    - appendix.qmd

bibliography: [references.bib, packages.bib]

theme:
  light: cosmo
  dark: superhero

editor: visual

