project:
  type: book
  output-dir: docs

book:
  title: "REDCap R Handbook"
  author: "Andreas Gammelgaard Damsbo"
  date:  "01-16-2023"
  search: true
  repo-url: https://github.com/agdamsbo/redcap-r-handbook/
  repo-actions: [edit]
  site-url: https://agdamsbo.github.io/redcap-r-handbook/
  chapters:
    - index.qmd
    - access.qmd
    - databases.qmd
    - advanced.qmd
    - references.qmd

bibliography: [references.bib, packages.bib]

format:
  html:
    theme: flatly

editor: visual

