project:
  type: book

book:
  title: "REDCap R Handbook"
  author: "Andreas Gammelgaard Damsbo"
  favicon: "/images/favicon.png"
  date: last-modified
  status: "drafting"
  search: true
  repo-url: https://github.com/agdamsbo/redcap-r-handbook/
  repo-actions: [edit]
  site-url: https://agdamsbo.github.io/redcap-r-handbook/
  chapters:
    - index.qmd
    - doc/access.qmd
    - part: doc/datahandling.qmd
      chapters:
        - doc/acquisition.qmd
    - part: doc/database.qmd
      chapters:
        - doc/dataset.qmd
        - doc/scratch.qmd
        - doc/advanced.qmd
  appendices:
    - doc/references.qmd
    - doc/appendix.qmd
    - LICENSE.md
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html

bibliography: [references.bib, packages.bib]

execute:
  freeze: auto

theme:
  light: cosmo
  dark: superhero

editor:
  markdown:
    wrap: 72
    canonical: true
